### ISSUE TITLE
what is the input label for target label mask?

### ISSUE THREAD

**Issue by alphapibeta** [ZitongYu/STVEN_rPPGNet#9]
[Step 2: Forward model and calculate the losses  ](https://github.com/ZitongYu/STVEN_rPPGNet/blob/088c20be7c768bf859bdf7dd51cc23c9e9290a0b/train_STVEN#L27)
 input 1: facial frames --> [3, 64, 128, 128]
### video_GroudTruth: the original video (before highly compressed)

•Can someone explain to me, how the target label mask is 5D?
•How do I prepare the dataset?

**Comment by wang-yu1016** [comment]
how to make binary skin labels
